/*
 * File: app/store/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.store.Navigation', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'ext5.store.override.Navigation',
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'navigation',
            root: {
                
            },
            fields: [
                {
                    name: 'id'
                }
            ]
        }, cfg)]);
    },

    /* BreadCrumb가 일반적인 TreeStore의 AJax요청 처리에 정상적으로 데이터가 설정되지 않는 문제를 해결한다. */
    initConfig: function(config) {
        var me = this;
        Ext.Ajax.request({
            url:  'resources/data/navigation.json',
            async: false,
            success: function (res, req) {
                var ret = Ext.JSON.decode(res.responseText);
                if ( ret.success ) {
                    config.root = ret.data;
                }
            }
        });
        this.callParent(arguments);
    }

});