/*
 * File: app/view/CodePreview.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.CodePreview', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.codePreview',

    requires: [
        'ext5.view.CodePreviewViewModel',
        'Ext.panel.Tool'
    ],

    config: {
        showTitle: true
    },

    viewModel: {
        type: 'codepreview'
    },
    bodyPadding: 5,
    bodyStyle: 'direction: ltr;',
    activeTab: 0,

    tools: [
        {
            xtype: 'tool',
            tooltip: 'Maximize example code content',
            type: 'maximize'
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processCodePreview1(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processCodePreview1: function(config) {
        // if(config.showTitle){
            config.title = "Details";
        // }

        console.log(config.showTitle);
        return config;
    }

});