/*
 * File: app/view/HeaderViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.HeaderViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.header',

    listen: {
        // #1
        controller: {
            // #2
            main: {
                // #3
                togglescreen: 'toggleScreen'// #4
            }
        }
    },

    init: function() {
        this.setConfig({control: {
            '[itemId=fullscreen]' : {
                click : 'onFullScreen'
            },
            '[itemId=originscreen]' : {
                click : 'onOriginScreen'
            },
            'button[itemId=godashboard]' : {
                click : 'goDashboard'
            }
        }});
    },

    onFullScreen: function() {
        var docElm = document.documentElement;

        if (docElm.requestFullscreen) {
            docElm.requestFullscreen();
        } else if (docElm.mozRequestFullScreen) {
            docElm.mozRequestFullScreen();
        } else if (docElm.webkitRequestFullScreen) {
            docElm.webkitRequestFullScreen();
        }
        this.toggleScreen(true);
    },

    onOriginScreen: function() {
        if (document.exitFullscreen) {
            document.exitFullscreen();
        }
        else if (document.mozCancelFullScreen) {
            document.mozCancelFullScreen();
        } else if (document.webkitCancelFullScreen) {
            document.webkitCancelFullScreen();
        }
        this.toggleScreen(false);
    },

    toggleScreen: function(fullscreen) {
        console.log('toggle...');
        Ext.each(Ext.ComponentQuery.query('[itemId=fullscreen]'), function (item) {
            item.setDisabled(fullscreen ? true : false);
        });
        Ext.each(Ext.ComponentQuery.query('[itemId=originscreen]'), function (item) {
            item.setDisabled(fullscreen ? false : true);
        });
    },

    goDashboard: function() {
        this.redirectTo('frame-dashboard');
    }

});
