/*
 * File: app/view/Header.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.Header', {
    extend: 'Ext.container.Container',
    alias: 'widget.frameheader',

    requires: [
        'ext5.view.HeaderViewModel',
        'ext5.view.HeaderViewController',
        'ext5.view.TopMenu',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.ProgressBar'
    ],

    controller: 'header',
    viewModel: {
        type: 'header'
    },
    reference: 'fullscreen',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'topmenu',
            flex: 1
        },
        {
            xtype: 'toolbar',
            flex: 1,
            items: [
                {
                    xtype: 'button',
                    itemId: 'fullscreen',
                    iconCls: 'button-icon-move'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'originscreen',
                    iconCls: 'button-icon-trackback'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    itemId: 'godashboard',
                    iconCls: 'button-icon-home'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    itemId: 'help',
                    iconCls: 'button-icon-help'
                },
                {
                    xtype: 'progressbar',
                    itemId: 'topprogressbar',
                    maxWidth: 400,
                    minWidth: 300,
                    text: 'Stand By...'
                }
            ]
        }
    ]

});