/*
 * File: app/view/TopMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.TopMenu', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.topmenu',

    requires: [
        'ext5.view.TopMenuViewModel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Separator'
    ],

    viewModel: {
        type: 'topmenu'
    },
    width: 400,

    items: [
        {
            xtype: 'button',
            cls: 'custom-button-text-bold',
            text: 'ExtJS Ria Application',
            menu: {
                xtype: 'menu',
                width: 200,
                items: [
                    {
                        xtype: 'menuitem',
                        iconCls: 'button-icon-film',
                        text: '애플리케이션 정보'
                    },
                    {
                        xtype: 'menuseparator'
                    },
                    {
                        xtype: 'menuitem',
                        iconCls: 'button-icon-display',
                        text: '보기설정',
                        menu: {
                            xtype: 'menu',
                            width: 120,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    reference: 'fullscreen',
                                    itemId: 'fullscreen',
                                    iconCls: 'button-icon-move',
                                    text: '전체보기 설정'
                                },
                                {
                                    xtype: 'menuitem',
                                    disabled: true,
                                    itemId: 'originscreen',
                                    iconCls: 'button-icon-trackback',
                                    text: '전체보기 해제'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'menuitem',
                        itemId: 'exit',
                        iconCls: 'button-icon-exit',
                        text: '프로그램 종료'
                    }
                ]
            }
        }
    ]

});