/*
 * File: app/view/saki/databinding/ext5style/MainViewViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.saki.databinding.ext5style.MainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sakidatabindingext5stylemainview',

    init: function() {
        // this.control({
        //     'sakidatabindingext5stylepersongrid': {
        //         select :'onPersonSelect'
        //     }
        // });
    },

    onGridButton: function(btn) {
        var action = btn.getItemId(),
            vm = this.getViewModel(),
            store = vm.getStore('persons'),
            record ;
        if('add' == action){
            record = store.insert(0, {})[0];
            vm.set('currentPerson', record);
        }
        if('reject' == action){
            store.rejectChanges();
        }
        if('commit' == action){
            store.commitChanges();
            record = vm.get('currentPerson');
            record.commit();
            record.reject();
        }
    },

    onFormButton: function(btn) {
        var person = this.getViewModel().get('currentPerson'),
            action = btn.getItemId();
        console.log('action', action);
        if(person && person.isModel){
            if('reject' === action){
                person.reject();
            }
            if('commit' === action){
                person.commit();
                person.reject();
            }
        }
    }

});
