/*
 * File: app/view/saki/databinding/ext5style/MainViewViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.saki.databinding.ext5style.MainViewViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.sakidatabindingext5stylemainview',

    requires: [
        'Ext.app.bind.Formula',
        'Ext.data.Store',
        'Ext.data.ChainedStore'
    ],

    data: {
        currentPerson: null,
        mytitle: '하하하하.'
    },

    formulas: {
        dirty: {
            get: function(data) {
                return data ? data.dirty: false;
            },
            bind: {
                bindTo: '{currentPerson}',
                deep: true
            }
        },
        storeDirty: {
            get: function(data) {
                console.log('storeDirty', this.getStore('persons').isDirty());
                return this.getStore('persons').isDirty();
            },
            bind: {
                bindTo: '{currentPerson}',
                deep: true
            }
        }
    },
    stores: {
        persons: {
            isDirty: function() {
                var dirty = this.getModifiedRecords().length;
                dirty = dirty || this.getNewRecords().length;
                dirty = dirty || this.getRemovedRecords().length;

                console.log('dirty', !!dirty);

                return !!dirty;
            },
            model: 'ext5.model.saki.databinding.PersonModel',
            data: [
                {
                    id: 1,
                    fname: 'John',
                    lname: 'Lenon',
                    age: 74
                },
                {
                    id: 2,
                    fname: 'Paul',
                    lname: 'McCartney',
                    age: 72
                },
                {
                    id: 3,
                    fname: 'George',
                    lname: 'Harrison',
                    age: 33
                },
                {
                    id: 4,
                    fname: 'Ringo',
                    lname: 'Starr',
                    age: 74
                }
            ]
        },
        personsChained: {
            source: '{persons}'
        }
    }

});