/*
 * File: app/view/saki/databinding/ext5style/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.saki.databinding.ext5style.MainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sakidatabindingext5stylemainview',

    requires: [
        'ext5.view.saki.databinding.ext5style.MainViewViewModel',
        'ext5.view.saki.databinding.ext5style.MainViewViewController',
        'ext5.view.saki.databinding.ext5style.PersonGrid',
        'ext5.view.saki.databinding.ext5style.PersonView',
        'ext5.view.saki.databinding.ext5style.PersonForm',
        'Ext.grid.Panel',
        'Ext.view.View',
        'Ext.form.Panel'
    ],

    controller: 'sakidatabindingext5stylemainview',
    viewModel: {
        type: 'sakidatabindingext5stylemainview'
    },
    cls: 'mainview',
    frame: true,
    height: 480,
    ui: 'default-framed',
    width: 740,
    title: 'ExtJS 5 Data Binding Example',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'sakidatabindingext5stylepersongrid',
                    flex: 1
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    autoScroll: true,
                    bind: {
                        title: '<b>{currentPerson.name}</b>'
                    },
                    items: [
                        {
                            xtype: 'sakidatabindingext5stylepersonview',
                            bind: {
                                currentPerson: '{currentPerson}',
                                store: '{personsChained}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            defaults: {
                flex: 1,
                margin: 5,
                border: true
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'personform',
                    flex: 1
                }
            ]
        }
    ]

});