/*
 * File: app/view/saki/bindingradio/FormView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.saki.bindingradio.FormView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sakibindingradioformview',

    requires: [
        'ext5.view.saki.bindingradio.FormViewViewModel',
        'Ext.XTemplate',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    config: {
        otherContent: [
            {
                type: 'Model',
                path: 'app/view/saki/bindingradio/FormViewViewModel.js'
            }
        ]
    },

    viewModel: {
        type: 'sakibindingradioformview'
    },
    height: 200,
    width: 400,
    bodyPadding: 10,
    title: 'My Form',

    items: [
        {
            xtype: 'component',
            height: 40,
            margin: 10,
            tpl: [
                '<div style="height:40px;background:{color}; border:1px solid #eeeeee"></div>'
            ],
            bind: {
                data: '{colorValue}'
            }
        },
        {
            xtype: 'radiogroup',
            padding: 10,
            defaults: {
                name: 'color'
            },
            fieldLabel: 'Color',
            labelAlign: 'top',
            columns: 3,
            bind: {
                value: '{colorValue}'
            },
            items: [
                {
                    xtype: 'radiofield',
                    boxLabel: 'Red',
                    inputValue: 'red'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Green',
                    inputValue: 'green'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Blue',
                    inputValue: 'blue'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Cyan',
                    inputValue: 'cyan'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Magenta',
                    inputValue: 'magenta'
                },
                {
                    xtype: 'radiofield',
                    boxLabel: 'Yellow',
                    inputValue: 'yellow'
                }
            ]
        }
    ]

});