/*
 * File: app/store/saki/databinding/ext4style/PersonStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.store.saki.databinding.ext4style.PersonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ext5.model.saki.databinding.PersonModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'saki.databinding.ext4style.PersonStore',
            model: 'ext5.model.saki.databinding.PersonModel',
            data: [
                {
                    id: 1,
                    fname: 'John',
                    lname: 'Lennon',
                    age: 74
                },
                {
                    id: 2,
                    fname: 'Paul',
                    lname: 'McCartney',
                    age: 72
                },
                {
                    id: 3,
                    fname: 'George',
                    lname: 'Harrison',
                    age: 71
                },
                {
                    id: 4,
                    fname: 'Ringo',
                    lname: 'Starr',
                    age: 74
                }
            ]
        }, cfg)]);
    }
});