/*
 * File: app/view/navigation/Breadcrumb.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.navigation.Breadcrumb', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.navigationbreadcrumb',

    requires: [
        'ext5.view.navigation.BreadcrumbViewModel',
        'Ext.toolbar.Breadcrumb'
    ],

    config: {
        selection: null
    },

    viewModel: {
        type: 'navigationbreadcrumb'
    },

    updateSelection: function(node) {
        if (this.rendered) {    // #14
            this._breadcrumbBar.setSelection(node); // #15
        }
    },

    initComponent: function() {
        var me = this;
        this.items = [
            {
                xtype: 'tool',
                type: 'down',
                tooltip: 'Switch to Tree View',
                listeners: {
                    click: 'showTreeNav'
                }
            },
            {
                xtype: 'breadcrumb',
                reference: 'toolbar',
                selection: this.getSelection(),
                flex: 1,
                store: 'Navigation'
            }
        ];
        this.callParent();

        this._breadcrumbBar = this.items.getAt(1);
    }

});