/*
 * File: app/view/navigation/Tree.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.navigation.Tree', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.navigationtree',

    requires: [
        'ext5.view.navigation.TreeViewModel',
        'Ext.tree.View',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'navigationtree'
    },
    minWidth: 100,
    width: 250,
    collapseFirst: false,
    collapsible: true,
    title: '샘플들',
    hideHeaders: true,
    rootVisible: false,
    useArrows: true,

    viewConfig: {

    },
    tools: [
        {
            xtype: 'tool',
            itemId: 'showBreadcrumbNav',
            tooltip: 'Switcher to Breadcrumb View',
            type: 'up'
        }
    ],

    initComponent: function() {
        Ext.apply(this, {
            store: 'Navigation'
        });
        this.callParent(arguments);
    }

});