/*
 * File: app/view/saki/databinding/ext4style/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ext5.view.saki.databinding.ext4style.MainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.saki_databinding_ext4style_mainview',

    requires: [
        'ext5.view.saki.databinding.ext4style.MainViewViewModel'
    ],

    viewModel: {
        type: 'sakidatabindingext4stylemainview'
    },
    cls: 'mainview',
    frame: true,
    height: 480,
    ui: 'default-framed',
    width: 740,
    title: 'ExtJS 5 Data Binding Example',

    initComponent: function() {
        var b=this,
            a={};
        Ext.apply(a,{
            layout:{
                type:"hbox",
                align:"stretch"
            },
            defaults:{
                flex:1
            },
            items:[{
                xtype:"container",
                layout:{
                    type:"vbox",
                    align:"stretch"
                },
                defaults:{
                    flex:1,
                    margin:5,
                    border: true
                },
                items:[{
                    title:"Editable Grid",
                    xtype:"persongridview",
                    glyph:61646
                },{
                    title:"DataView",
                    glyph:61449,
                    layout:"fit",
        //             bind: {
        //                 title: '<b>{currentPerson.name}</b>'
        //             },
                    cls:"person-dataview",
                    items:[{
                        xtype:"persondataview"
                    }]
                }]
            },{
                xtype:"container",
                layout:{
                    type:"vbox",
                    align:"stretch"
                },
                defaults:{
                    flex:1,
                    margin:5
                },
                items:[{
                    title:"Form",
                    xtype:"personformview",
                    glyph:61508,
                    frame:true
                },{
                    title:"Data Panel",
                    xtype:"personpanel",
                    glyph:61686
                }]
            }]
        });
        Ext.apply(b,a);
        this.callParent(arguments);
    }

});